projects:
  AppSyncSimpleTransform-dev:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: graphql/com/amazonaws/amplify/generated/graphql
        region: eu-central-1
        apiId: t6foogt25ja2xbe4kqsar52upm
        maxDepth: 2
extensions:
  amplify:
    version: 3
